version: '3.1'
services:
    db:
        image: percona:5.7
        restart: always
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: yildiz
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080