---
swagger: '2.0'
info:
  title: YildizDB HTTP interface
  description: Graph Database on top of Google Bigtable
  version: 8.2.3
host: localhost
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  "/node/{identifier}":
    get:
      parameters:
      - name: identifier
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              id:
                type: number
              identifier:
                type: string
              data:
                type: object
                additionalProperties: true
              ttld:
                type: boolean
              created_at:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Node
    delete:
      parameters:
      - name: identifier
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
            additionalProperties: false
          description: Default Response
      tags:
      - Node
  "/node/counts":
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Node
  "/node":
    post:
      responses:
        '200':
          schema:
            type: object
            properties:
              id:
                type: number
              identifier:
                type: string
              data:
                type: object
                additionalProperties: true
              ttld:
                type: boolean
              created_at:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Node
  "/edge/{leftId}/{rightId}/{relation}":
    get:
      parameters:
      - name: leftId
        in: path
        required: true
        type: string
      - name: rightId
        in: path
        required: true
        type: string
      - name: relation
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              id:
                type: string
              depth:
                type: number
              relation:
                type: string
              data:
                type: object
                additionalProperties: true
              ttld:
                type: boolean
              created_at:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
    delete:
      parameters:
      - name: leftId
        in: path
        required: true
        type: number
      - name: rightId
        in: path
        required: true
        type: number
      - name: relation
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/edge/counts":
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Edge
  "/edge":
    post:
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/edge/depth/increase":
    put:
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/edge/depth/decrease":
    put:
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/edge/left/{id}/{relation}":
    get:
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: relation
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              edges:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    depth:
                      type: number
                    relation:
                      type: string
                    data:
                      type: object
                      additionalProperties: true
                    ttld:
                      type: boolean
                    created_at:
                      type: string
                    right_node_id:
                      type: number
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/edge/right/{id}/{relation}":
    get:
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: relation
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              edges:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    depth:
                      type: number
                    relation:
                      type: string
                    data:
                      type: object
                      additionalProperties: true
                    ttld:
                      type: boolean
                    created_at:
                      type: string
                    left_node_id:
                      type: number
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/edge/both/{id}/{relation}":
    get:
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: relation
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              edges:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    depth:
                      type: number
                    relation:
                      type: string
                    data:
                      type: object
                      additionalProperties: true
                    ttld:
                      type: boolean
                    created_at:
                      type: string
                    right_node_id:
                      type: number
                    left_node_id:
                      type: number
            additionalProperties: false
          description: Default Response
      tags:
      - Edge
  "/access/translated-edge-info":
    post:
      parameters:
      - name: body
        in: body
        description: Default Response
        schema:
          properties:
            values:
              type: array
              items:
                type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              identifiers:
                type: array
                items:
                  type: object
                  additionalProperties: true
              nodes:
                type: array
                items:
                  type: object
                  additionalProperties: true
              edges:
                type: array
                items:
                  type: object
                  additionalProperties: true
            additionalProperties: false
          description: Default Response
      tags:
      - Access
  "/access/upsert-singular-relation":
    post:
      parameters:
      - name: body
        in: body
        schema:
          properties:
            leftNodeIdentifierVal:
              type: string
            rightNodeIdentifierVal:
              type: string
            leftNodeData:
              type: object
              additionalProperties: true
            rightNodeData:
              type: object
              additionalProperties: true
            ttld:
              type: boolean
            relation:
              type: string
            edgeData:
              type: object
              additionalProperties: true
            depthBeforeCreation:
              type: boolean
            isPopularRightNode:
              type: boolean
            edgeTime:
              type: number
      responses:
        '200':
          schema:
            type: object
            properties: {}
            additionalProperties: true
          description: Default Response
      tags:
      - Access
  "/access/node/{identifier}":
    delete:
      parameters:
      - name: identifier
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
          description: Default Response
      tags:
      - Access
  "/":
    get:
      responses:
        '200':
          schema:
            type: object
            properties:
              version:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Admin
  "/admin/health":
    get:
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Admin
  "/admin/healthcheck":
    get:
      responses:
        '200':
          schema:
            type: object
            properties:
              status:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Admin
  "/admin/metrics":
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Admin
  "/admin/authcheck":
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Admin
  "/admin/metadata/counts":
    get:
      responses:
        '200':
          schema:
            type: object
            properties:
              edges:
                type: number
              nodes:
                type: number
              ttls:
                type: number
            additionalProperties: false
          description: Default Response
      tags:
      - Admin
  "/admin/reset-tables":
    post:
      responses:
        '200':
          description: Default Response
      tags:
      - Admin
  "/translator/{identifier}":
    get:
      parameters:
      - name: identifier
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              identifier:
                type: number
              value:
                type: string
              data:
                type: object
                additionalProperties: true
              ttld:
                type: boolean
              created_at:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Translator
    delete:
      parameters:
      - name: identifier
        in: path
        required: true
        type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              success:
                type: boolean
            additionalProperties: false
          description: Default Response
      tags:
      - Translator
  "/translator/counts":
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Translator
  "/translator/translate-and-store":
    post:
      responses:
        '200':
          schema:
            type: object
            properties:
              identifier:
                type: number
              value:
                type: string
              data:
                type: object
                additionalProperties: true
              ttld:
                type: boolean
              created_at:
                type: string
            additionalProperties: false
          description: Default Response
      tags:
      - Translator
